### ISSUE TITLE
KeyError when no ipv6 address

### ISSUE THREAD

**Issue by yvespp** [vmware/cloud-init-vmware-guestinfo#29]
advertise_local_ip_addrs throws this error on our vms:
```
2019-12-11 11:47:07,544 - util.py[DEBUG]: failed stage init
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 375, in main_init
    init.setup_datasource()
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 374, in setup_datasource
    self.datasource.setup(is_new_instance=self.is_new_instance())
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 151, in setup
    advertise_local_ip_addrs(host_info)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 280, in advertise_local_ip_addrs
    local_ipv6 = host_info[LOCAL_IPV6]
KeyError: 'local-ipv6'
```
We have disable ipv6 on this host.

I suspect this was introduce with https://github.com/vmware/cloud-init-vmware-guestinfo/pull/26
I think the code here https://github.com/vmware/cloud-init-vmware-guestinfo/pull/26/files#diff-887b9ab215181ea8c8772e608c0408fdR275 should check if host_info has the keys local-ipv4 and local-ipv6 before accessing them.

**Comment by akutz** [comment]
Hi @yvespp ,

I wanted to say thank you for both this and the other PR. I stupidly conflated Python with Golang and forgot you can't reference a missing key with the index operation in the former.

**Comment by yvespp** [comment]
You are welcome!
It happens, I tend to forgett the semicolons in java...
