### ISSUE TITLE
version 1.2.0 got function error  when cloudinit is trying to get metadata and userdata

### ISSUE THREAD

**Issue by jenningsloy318** [vmware/cloud-init-vmware-guestinfo#32]
Hi ,

OS: RHEL 7.4
Cloud-init: 18.5 /19.4 (both version are tested, but not working)

after upgrade version 1.2.0, the cloudinit is stopping working, the error log from /var/log/cloud-init.log 
```
2020-01-13 03:29:00,673 - util.py[DEBUG]: Cloud-init v. 18.5-71.el7 running 'init-local' at Mon, 13 Jan 2020 03:29:00 +0000. Up 13.83 seconds.
2020-01-13 03:29:00,673 - main.py[DEBUG]: No kernel command line url found.
2020-01-13 03:29:00,673 - main.py[DEBUG]: Closing stdin.
2020-01-13 03:29:00,688 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2020-01-13 03:29:00,689 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2020-01-13 03:29:00,689 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
2020-01-13 03:29:00,689 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2020-01-13 03:29:00,689 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2020-01-13 03:29:00,689 - stages.py[DEBUG]: no cache found
2020-01-13 03:29:00,690 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2020-01-13 03:29:00,690 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2020-01-13 03:29:00,715 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>
2020-01-13 03:29:00,715 - __init__.py[DEBUG]: Looking for data source in: ['VMwareGuestInfo'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2020-01-13 03:29:00,757 - __init__.py[DEBUG]: Searching for local data source in: []
2020-01-13 03:29:00,757 - main.py[DEBUG]: No local datasource found
2020-01-13 03:29:00,758 - util.py[DEBUG]: Reading from /sys/class/net/ens192/name_assign_type (quiet=False)
2020-01-13 03:29:00,758 - __init__.py[DEBUG]: Found unstable nic names: ['ens192']; calling udevadm settle
2020-01-13 03:29:00,759 - util.py[DEBUG]: Running command ['udevadm', 'settle'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:00,764 - util.py[DEBUG]: Waiting for udev events to settle took 0.006 seconds
2020-01-13 03:29:00,765 - util.py[DEBUG]: Reading from /sys/class/net/ens192/carrier (quiet=False)
2020-01-13 03:29:00,765 - util.py[DEBUG]: Reading from /sys/class/net/ens192/dormant (quiet=False)
2020-01-13 03:29:00,765 - util.py[DEBUG]: Reading from /sys/class/net/ens192/operstate (quiet=False)
2020-01-13 03:29:00,765 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens192/operstate
2020-01-13 03:29:00,766 - util.py[DEBUG]: Reading from /sys/class/net/ens192/address (quiet=False)
2020-01-13 03:29:00,766 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens192/address
2020-01-13 03:29:00,766 - util.py[DEBUG]: Reading from /sys/class/net/ens192/address (quiet=False)
2020-01-13 03:29:00,766 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens192/address
2020-01-13 03:29:00,766 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'subnets': [{'type': 'dhcp'}], 'type': 'physical', 'name': 'ens192', 'mac_address': '00:50:56:ad:60:c8'}]}
2020-01-13 03:29:00,766 - util.py[DEBUG]: Reading from /sys/class/net/ens192/device/device (quiet=False)
2020-01-13 03:29:00,766 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens192/device/device
2020-01-13 03:29:00,766 - util.py[DEBUG]: Reading from /sys/class/net/ens192/addr_assign_type (quiet=False)
2020-01-13 03:29:00,767 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens192/addr_assign_type
2020-01-13 03:29:00,767 - util.py[DEBUG]: Reading from /sys/class/net/ens192/uevent (quiet=False)
2020-01-13 03:29:00,767 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/ens192/uevent
2020-01-13 03:29:00,767 - util.py[DEBUG]: Reading from /sys/class/net/ens192/address (quiet=False)
2020-01-13 03:29:00,767 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens192/address
2020-01-13 03:29:00,767 - util.py[DEBUG]: Reading from /sys/class/net/ens192/device/device (quiet=False)
2020-01-13 03:29:00,767 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens192/device/device
2020-01-13 03:29:00,767 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2020-01-13 03:29:00,767 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2020-01-13 03:29:00,768 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2020-01-13 03:29:00,768 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2020-01-13 03:29:00,768 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2020-01-13 03:29:00,768 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2020-01-13 03:29:00,768 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2020-01-13 03:29:00,768 - util.py[DEBUG]: Reading from /sys/class/net/ens192/operstate (quiet=False)
2020-01-13 03:29:00,768 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens192/operstate
2020-01-13 03:29:00,768 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2020-01-13 03:29:00,769 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2020-01-13 03:29:00,769 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:00,793 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:00,800 - __init__.py[DEBUG]: no work necessary for renaming of [['00:50:56:ad:60:c8', 'ens192', 'vmxnet3', '0x07b0']]
2020-01-13 03:29:00,801 - stages.py[INFO]: Applying network configuration from fallback bringup=False: {'version': 1, 'config': [{'subnets': [{'type': 'dhcp'}], 'type': 'physical', 'name': 'ens192', 'mac_address': '00:50:56:ad:60:c8'}]}
2020-01-13 03:29:00,804 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2020-01-13 03:29:00,804 - util.py[DEBUG]: Read 532 bytes from /etc/os-release
2020-01-13 03:29:00,807 - __init__.py[DEBUG]: Selected renderer 'sysconfig' from priority list: None
2020-01-13 03:29:00,812 - util.py[DEBUG]: Writing to /etc/sysconfig/network-scripts/ifcfg-ens192 - wb: [644] 193 bytes
2020-01-13 03:29:00,814 - util.py[DEBUG]: Reading from /etc/resolv.conf (quiet=False)
2020-01-13 03:29:00,814 - util.py[DEBUG]: Read 95 bytes from /etc/resolv.conf
2020-01-13 03:29:00,814 - util.py[DEBUG]: Writing to /etc/resolv.conf - wb: [644] 95 bytes
2020-01-13 03:29:00,815 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 98 bytes
2020-01-13 03:29:00,820 - util.py[DEBUG]: Writing to /etc/sysconfig/network - wb: [644] 86 bytes
2020-01-13 03:29:00,820 - main.py[DEBUG]: [local] Exiting without datasource
2020-01-13 03:29:00,832 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2020-01-13 03:29:00,832 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2020-01-13 03:29:00,832 - util.py[DEBUG]: cloud-init mode 'init' took 0.323 seconds (0.32)
2020-01-13 03:29:00,832 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2020-01-13 03:29:01,114 - util.py[DEBUG]: Cloud-init v. 18.5-71.el7 running 'init' at Mon, 13 Jan 2020 03:29:01 +0000. Up 14.28 seconds.
2020-01-13 03:29:01,114 - main.py[DEBUG]: No kernel command line url found.
2020-01-13 03:29:01,114 - main.py[DEBUG]: Closing stdin.
2020-01-13 03:29:01,115 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2020-01-13 03:29:01,115 - util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:01,121 - util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:01,124 - util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2020-01-13 03:29:01,129 - main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
2020-01-13 03:29:01,129 - main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
2020-01-13 03:29:01,129 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2020-01-13 03:29:01,129 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2020-01-13 03:29:01,130 - stages.py[DEBUG]: no cache found
2020-01-13 03:29:01,130 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2020-01-13 03:29:01,130 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2020-01-13 03:29:01,132 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>
2020-01-13 03:29:01,132 - __init__.py[DEBUG]: Looking for data source in: ['VMwareGuestInfo'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2020-01-13 03:29:01,133 - __init__.py[DEBUG]: Searching for network data source in: []
2020-01-13 03:29:01,133 - util.py[WARNING]: No instance datasource found! Likely bad things to come!
2020-01-13 03:29:01,133 - util.py[DEBUG]: No instance datasource found! Likely bad things to come!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/cmd/main.py", line 323, in main_init
    init.fetch(existing=existing)
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 351, in fetch
    return self._get_data_source(existing=existing)
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 261, in _get_data_source
    pkg_list, self.reporter)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 741, in find_source
    raise DataSourceNotFoundException(msg)
DataSourceNotFoundException: Did not find any data source, searched classes: ()
2020-01-13 03:29:01,167 - util.py[DEBUG]: Reading from /sys/class/net/ens192/name_assign_type (quiet=False)
2020-01-13 03:29:01,167 - __init__.py[DEBUG]: Found unstable nic names: ['ens192']; calling udevadm settle
2020-01-13 03:29:01,168 - util.py[DEBUG]: Running command ['udevadm', 'settle'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:01,177 - util.py[DEBUG]: Waiting for udev events to settle took 0.009 seconds
2020-01-13 03:29:01,177 - util.py[DEBUG]: Reading from /sys/class/net/ens192/carrier (quiet=False)
2020-01-13 03:29:01,177 - util.py[DEBUG]: Reading from /sys/class/net/ens192/dormant (quiet=False)
2020-01-13 03:29:01,178 - util.py[DEBUG]: Reading from /sys/class/net/ens192/operstate (quiet=False)
2020-01-13 03:29:01,178 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens192/operstate
2020-01-13 03:29:01,178 - util.py[DEBUG]: Reading from /sys/class/net/ens192/address (quiet=False)
2020-01-13 03:29:01,178 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens192/address
2020-01-13 03:29:01,178 - util.py[DEBUG]: Reading from /sys/class/net/ens192/address (quiet=False)
2020-01-13 03:29:01,178 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens192/address
2020-01-13 03:29:01,179 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'subnets': [{'type': 'dhcp'}], 'type': 'physical', 'name': 'ens192', 'mac_address': '00:50:56:ad:60:c8'}]}
2020-01-13 03:29:01,179 - util.py[DEBUG]: Reading from /sys/class/net/ens192/device/device (quiet=False)
2020-01-13 03:29:01,179 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens192/device/device
2020-01-13 03:29:01,179 - util.py[DEBUG]: Reading from /sys/class/net/ens192/addr_assign_type (quiet=False)
2020-01-13 03:29:01,179 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens192/addr_assign_type
2020-01-13 03:29:01,179 - util.py[DEBUG]: Reading from /sys/class/net/ens192/uevent (quiet=False)
2020-01-13 03:29:01,179 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/ens192/uevent
2020-01-13 03:29:01,180 - util.py[DEBUG]: Reading from /sys/class/net/ens192/address (quiet=False)
2020-01-13 03:29:01,180 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens192/address
2020-01-13 03:29:01,180 - util.py[DEBUG]: Reading from /sys/class/net/ens192/device/device (quiet=False)
2020-01-13 03:29:01,180 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens192/device/device
2020-01-13 03:29:01,180 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2020-01-13 03:29:01,180 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2020-01-13 03:29:01,180 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2020-01-13 03:29:01,180 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2020-01-13 03:29:01,181 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2020-01-13 03:29:01,181 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2020-01-13 03:29:01,181 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2020-01-13 03:29:01,181 - util.py[DEBUG]: Reading from /sys/class/net/ens192/operstate (quiet=False)
2020-01-13 03:29:01,181 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/ens192/operstate
2020-01-13 03:29:01,181 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
2020-01-13 03:29:01,181 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
2020-01-13 03:29:01,182 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:01,186 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
2020-01-13 03:29:01,190 - __init__.py[DEBUG]: no work necessary for renaming of [['00:50:56:ad:60:c8', 'ens192', 'vmxnet3', '0x07b0']]
2020-01-13 03:29:01,190 - stages.py[INFO]: Applying network configuration from fallback bringup=True: {'version': 1, 'config': [{'subnets': [{'type': 'dhcp'}], 'type': 'physical', 'name': 'ens192', 'mac_address': '00:50:56:ad:60:c8'}]}
2020-01-13 03:29:01,191 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2020-01-13 03:29:01,191 - util.py[DEBUG]: Read 532 bytes from /etc/os-release
2020-01-13 03:29:01,192 - __init__.py[DEBUG]: Selected renderer 'sysconfig' from priority list: None
2020-01-13 03:29:01,198 - util.py[DEBUG]: Writing to /etc/sysconfig/network-scripts/ifcfg-ens192 - wb: [644] 193 bytes
2020-01-13 03:29:01,199 - util.py[DEBUG]: Reading from /etc/resolv.conf (quiet=False)
2020-01-13 03:29:01,199 - util.py[DEBUG]: Read 95 bytes from /etc/resolv.conf
2020-01-13 03:29:01,199 - util.py[DEBUG]: Writing to /etc/resolv.conf - wb: [644] 95 bytes
2020-01-13 03:29:01,200 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 98 bytes
2020-01-13 03:29:01,201 - util.py[DEBUG]: Writing to /etc/sysconfig/network - wb: [644] 86 bytes
2020-01-13 03:29:01,202 - main.py[DEBUG]: [net] Exiting without datasource
2020-01-13 03:29:01,203 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2020-01-13 03:29:01,203 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2020-01-13 03:29:01,203 - util.py[DEBUG]: cloud-init mode 'init' took 0.149 seconds (0.15)
2020-01-13 03:29:01,204 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
```

 `vmtoolsd --cmd "info-get guestinfo.metadata" | base64 -d | zcat - ` and  `vmtoolsd --cmd "info-get guestinfo.userdata" | base64 -d | zcat -` can get correct metadata and userdata, but not applied to system.

and this is working on release 1.1.0.

**Comment by jenningsloy318** [comment]
find out the missing package deepmerge, after install it, issue is fixed
