### ISSUE TITLE
CentOS 7 doesn't appear to be reading the GuestInfo Datasource

### ISSUE THREAD

**Issue by alexholliz** [vmware/cloud-init-vmware-guestinfo#41]
I've been working on building a CentOS 7 template that we can clone with terraform and use cloud-init scripts with. I'm seeing this error when we attempt to clone the template and pass cloud init data as metadata/userdata yamls:

```
2020-05-01 17:27:01,747 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceVMwareGuestInfo.DataSourceVMwareGuestInfo'> failed
2020-05-01 17:27:01,747 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceVMwareGuestInfo.DataSourceVMwareGuestInfo'> failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 733, in find_source
    if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 622, in update_metadata
    result = self.get_data()
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 82, in get_data
    self.metadata = json.loads(metadata)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Here's the relevant part of our Terraform config:
```
  clone {
    template_uuid = data.vsphere_virtual_machine.linux-vm-template.id
  }

  extra_config = {
      "guestinfo.metadata"          = base64gzip(file("${path.module}/templates/metadata.yaml"))
      "guestinfo.metadata.encoding" = "gzip+base64"
      "guestinfo.userdata"          = base64gzip(file("${path.module}/templates/userdata.yaml"))
      "guestinfo.userdata.encoding" = "gzip+base64"
  }
}
```

And finally, here's the packer packages we're installing into the template, along with the last step of the provisioner before it shuts down the vm and turns it into a vmware template:

```
%post
#sudo yum upgrade -y
chkconfig ntpd on
chkconfig sshd on
chkconfig ypbind on
chkconfig iptables off
chkconfig ip6tables off
chkconfig yum-updatesd off
chkconfig haldaemon off
chkconfig mcstrans off
chkconfig sysstat off
# Install vmware guest tools
echo "Installing VM Tools..."
# Install open-vm-tools, required to detect IP when building on ESXi
sudo yum -y install epel-release open-vm-tools perl python python3-pip openssh-server curl
sudo systemctl enable vmtoolsd
sudo systemctl start vmtoolsd
%end
```
and
```
  "provisioners": [

    {
      "type": "shell",
      "inline": [
        "sudo yum -y install https://github.com/vmware/cloud-init-vmware-guestinfo/releases/download/v1.1.0/cloud-init-vmware-guestinfo-1.1.0-1.el7.noarch.rpm"
      ]
    },

    {
      "type": "shell",
      "inline": [
        "sudo cloud-init clean"
      ]
    }

  ]
}
```

**Comment by foxalfabravo** [comment]
Hello there

I use Centos7/cloudinit/DataSourceVMwareGuestInfo on a lot of different appliances, and 1.1.0 it works fine

Did you check if the tags were readable from the guest ?
```
vmware-rpctool 'info-get guestinfo.metadata'
```

**Comment by ghost** [comment]
@foxalfabravo 

I'm having the same issue as @alexholliz is and running that command produces base64 encoded text, which decoded looks like this

![image](https://user-images.githubusercontent.com/25828043/83459027-6cd09200-a418-11ea-8580-c353f61d9b29.png)

**Comment by ghost** [comment]
Turns out that installing the RPM version doesn't work. Installing from the install script which installs a newer version of the datasource does work and cloudinit now seems to function properly

**Comment by alexholliz** [comment]
I can confirm what @tmashos was saying; the RPM does not work. I got a packer template working with the curl install: https://github.com/alexholliz/centos-7-cloudinit

**Comment by foxalfabravo** [comment]
Ok I nailed it - I just found out that it was working using an older cloud-init package (wrong packer file)- Pull request submitted
