### ISSUE TITLE
ImportError: cannot import name UnrewindableBodyError on RedHat 7.8

### ISSUE THREAD

**Issue by patsevanton** [vmware/cloud-init-vmware-guestinfo#64]
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)

yum install https://github.com/vmware/cloud-init-vmware-guestinfo/releases/download/v1.1.0/cloud-init-vmware-guestinfo-1.1.0-1.el7.noarch.rpm

```
journalctl -u cloud-init-local
-- Logs begin at Mon 2020-11-30 08:46:03 MSK, end at Mon 2020-11-30 10:01:01 MSK. --
Nov 30 08:46:07 rhel-78-16g systemd[1]: Starting Initial cloud-init job (pre-networking)...
Nov 30 08:46:07 rhel-78-16g python2[773]: detected unhandled Python exception in '/usr/bin/cloud-init'
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: Traceback (most recent call last):
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/bin/cloud-init", line 9, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: load_entry_point('cloud-init==19.4', 'console_scripts', 'cloud-init')()
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: return get_distribution(dist).load_entry_point(group, name)
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: return ep.load()
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: entry = __import__(self.module_name, globals(),globals(), ['__name__'])
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/cloudinit/cmd/main.py", line 26, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from cloudinit import netinfo
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/cloudinit/netinfo.py", line 15, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from cloudinit.net.network_state import net_prefix_to_ipv4_mask
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/cloudinit/net/__init__.py", line 14, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from cloudinit.net.network_state import mask_to_net_prefix
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 16, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from cloudinit import util
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 48, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from cloudinit import url_helper
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/cloudinit/url_helper.py", line 14, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: import requests
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from . import utils
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from .exceptions import InvalidURL
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from urllib3.exceptions import HTTPError as BaseHTTPError
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from .connectionpool import (
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 31, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from .connection import (
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 45, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from .util.ssl_ import (
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 5, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from .request import SKIP_HEADER, SKIPPABLE_HEADERS, make_headers
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: File "/usr/lib/python2.7/site-packages/urllib3/util/request.py", line 5, in <module>
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: from ..exceptions import UnrewindableBodyError
Nov 30 08:46:08 rhel-78-16g cloud-init[773]: ImportError: cannot import name UnrewindableBodyError
Nov 30 08:46:08 rhel-78-16g systemd[1]: cloud-init-local.service: main process exited, code=exited, status=1/FAILURE
Nov 30 08:46:08 rhel-78-16g systemd[1]: Failed to start Initial cloud-init job (pre-networking).
Nov 30 08:46:08 rhel-78-16g systemd[1]: Unit cloud-init-local.service entered failed state.
Nov 30 08:46:08 rhel-78-16g systemd[1]: cloud-init-local.service failed.
```

**Comment by akutz** [comment]
This issue is being closed because this datasource has been merged into cloud-init (https://github.com/canonical/cloud-init/pull/953):

| Component | Source | Tests |
|---|---|---|
| Datasource | [DataSourceVMware.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceVMware.py) | [test_vmware.py](https://github.com/canonical/cloud-init/blob/main/tests/unittests/test_datasource/test_vmware.py) |
| Identification | [ds-identify](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tools/ds-identify#L1367-L1439) | [test_ds_identify.py](https://github.com/canonical/cloud-init/blob/b9d308b4d61d22bacc05bcae59819755975631f8/tests/unittests/test_ds_identify.py#L652-L694) |
| Documentation | [vmware.rst](https://github.com/canonical/cloud-init/blob/main/doc/rtd/topics/datasources/vmware.rst) | |

In order to participate in the growth of this datasource moving forward, please:

* Ask a question in the [``#cloud-init`` IRC channel on Libera](https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init)
* Search the cloud-init [mailing list archive](https://lists.launchpad.net/cloud-init/)
* Join the [cloud-init mailing list](https://launchpad.net/~cloud-init)
* Report issues with [Launchpad](https://bugs.launchpad.net/cloud-init/+filebug)

Once again, many thanks to the wonderful community that has grown around this datasource, and I look forward to seeing everyone in the new cloud-init forums!
